# -*- coding: utf-8 -*-
"""Glaucoma_AI_Screening_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysOEc2kORU1lKpi8Okv5Gapwoh9zeS80
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

test_datagen = ImageDataGenerator(rescale=1./255)

train_data = train_datagen.flow_from_directory(
    "/content/drive/MyDrive/glaucoma_dataset/training_set",
    target_size=(224,224),
    batch_size=32,
    class_mode='binary'
)

val_data = test_datagen.flow_from_directory(
    "/content/drive/MyDrive/glaucoma_dataset/test_set",
    target_size=(224,224),
    batch_size=32,
    class_mode='binary'
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

model = Sequential()

model.add(Conv2D(32,(3,3),activation='relu',input_shape=(224,224,3)))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(128,(3,3),activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Flatten())

model.add(Dense(128,activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(1,activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=20
)

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title("Glaucoma Detection Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend(["Training Accuracy","Validation Accuracy"])

plt.show()

from tensorflow.keras.preprocessing import image
import numpy as np

# Path to the image
img_path = "/content/drive/MyDrive/glaucoma_dataset/test_set/normal/r2_Im025.png"

# Load image
img = image.load_img(img_path, target_size=(224,224))

# Convert image to array
img_array = image.img_to_array(img)

# Normalize and reshape
img_array = np.expand_dims(img_array, axis=0) / 255.0

# Predict
prediction = model.predict(img_array)

# Result
if prediction[0][0] > 0.5:
    print("Prediction: Glaucoma")
else:
    print("Prediction: Normal Eye")

model.save("glaucoma_cnn_model.h5")

loss, accuracy = model.evaluate(val_data)

print("Test Accuracy:", accuracy)

""" ***Explainable AI(Grad-CAM - through saliency map
 )***
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image

img_path = "/content/drive/MyDrive/glaucoma_dataset/test_set/normal/r2_Im025.png"

img = image.load_img(img_path, target_size=(224,224))
img_array = image.img_to_array(img)

img_array = img_array / 255.0
img_array = np.expand_dims(img_array, axis=0)

prediction = model.predict(img_array)

risk_score = prediction[0][0] * 100

print("Glaucoma Risk Score:", round(risk_score,2), "%")

if risk_score > 50:
    print("Diagnosis: Glaucoma Suspected")
else:
    print("Diagnosis: Normal Eye")

img_tensor = tf.convert_to_tensor(img_array)

with tf.GradientTape() as tape:
    tape.watch(img_tensor)
    prediction = model(img_tensor)

grads = tape.gradient(prediction, img_tensor)

saliency = tf.reduce_max(tf.abs(grads), axis=-1)[0]

plt.imshow(saliency, cmap="hot")
plt.title("Explainable AI Saliency Map")
plt.axis("off")
plt.show()

import cv2
import matplotlib.pyplot as plt
import numpy as np

# normalize saliency
saliency = np.abs(saliency)
saliency = (saliency - saliency.min()) / (saliency.max() - saliency.min())

# resize saliency to image size
saliency_resized = cv2.resize(saliency, (224,224))

# convert to heatmap
heatmap = cv2.applyColorMap(np.uint8(255 * saliency_resized), cv2.COLORMAP_JET)

# load original image
original = cv2.imread(img_path)
original = cv2.resize(original,(224,224))

# overlay heatmap
overlay = cv2.addWeighted(original, 0.6, heatmap, 0.4, 0)

plt.figure(figsize=(10,4))

plt.subplot(1,3,1)
plt.title("Input Image")
plt.imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))
plt.axis("off")

plt.subplot(1,3,2)
plt.title("Saliency Heatmap")
plt.imshow(cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB))
plt.axis("off")

plt.subplot(1,3,3)
plt.title("AI Focus Region")
plt.imshow(cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB))
plt.axis("off")

plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

# load original image
original = cv2.imread(img_path)

# resize saliency to match image
saliency_resized = cv2.resize(saliency,(original.shape[1],original.shape[0]))

# normalize
saliency_resized = (saliency_resized - saliency_resized.min()) / (saliency_resized.max() - saliency_resized.min())

# convert to heatmap
heatmap = cv2.applyColorMap(np.uint8(255*saliency_resized), cv2.COLORMAP_JET)

# overlay heatmap on image
overlay = cv2.addWeighted(original,0.6,heatmap,0.4,0)

# display
plt.imshow(cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.title("Explainable AI Glaucoma Region")
plt.show()

"""**Interface**"""

!pip install gradio

import gradio as gr
import cv2
import numpy as np

def glaucoma_detection(img):

    img_resized = cv2.resize(img,(224,224))
    img_array = img_resized / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)[0][0]

    risk_score = prediction * 100

    if risk_score > 50:
        diagnosis = "Glaucoma Suspected"
        confidence = "High"
    else:
        diagnosis = "Normal Eye"
        confidence = "Low"

    # -------- Explainable AI --------
    img_tensor = tf.convert_to_tensor(img_array)

    with tf.GradientTape() as tape:
        tape.watch(img_tensor)
        preds = model(img_tensor)
        loss = preds[:,0]

    grads = tape.gradient(loss, img_tensor)

    saliency = tf.reduce_max(tf.abs(grads), axis=-1)[0].numpy()

    saliency = (saliency - saliency.min()) / (saliency.max() - saliency.min())

    heatmap = cv2.applyColorMap(np.uint8(255*saliency), cv2.COLORMAP_JET)

    heatmap = cv2.resize(heatmap,(224,224))

    overlay = cv2.addWeighted(img_resized,0.6,heatmap,0.4,0)

    report = f"""
## 🧠 AI Glaucoma Screening Report

Diagnosis: {diagnosis}

Risk Score: {risk_score:.2f} %

Confidence Level: {confidence}

⚠️ This AI system is designed for early glaucoma screening.
Clinical confirmation by an ophthalmologist is recommended.
"""

    return img_resized, heatmap, overlay, report

interface = gr.Interface(
    fn=glaucoma_detection,
    inputs=gr.Image(type="numpy"),
    outputs=[
        gr.Image(label="Input Image"),
        gr.Image(label="Saliency Heatmap"),
        gr.Image(label="AI Focus Region"),
        gr.Markdown()
    ],
    title="Offline AI Glaucoma Detection System",
    description="Upload a retinal fundus image to detect glaucoma risk"
)

interface.launch()